const vulgarWords = [
  "Bhosdike",
  "bsdk",
  "Kutte",
  "Harmkhor",
  "Chutiya",
  "Gandu",
  "Madarchod",
  "Behenchod",
  "Sala",
  "Randi",
  "Bkl",
  "Lund",
  'Madharchod',
  "Bhadwa",
  "Teri Maa Ki",
  "Teri Behen Ki",
  "Kamina",
  "Harami",
  "Ullu ke pathe",
  "Gadha",
  "Hijra",
  "Maa ke laude",
  "Bhosada",
  "Chut",
  'Chutiye',
  "Chutmarika",
  "Chut ke dhakkan",
  "Lauda",
  "Laude ka",
  "Bhadwe",
  "Randi ka bacha",
  "Chut ke pasine",
  "Gand",
  "Gand marwane",
  "Gand faad",
  "Gand me danda",
  "Gand me goli",
  "Gand me le",
  "Gand me ghusa",
  "Gand me ungli",
  "Gand me aag",
  "Gand me jalan",
  "Gand me khujli",
  "Gand me supari",
  "Gand me bomb",
  "Gand me patakha",
  "Gand me rocket",
  "Gand me missile",
  "Gand me firecracker",
  "Gand me dynamite",
  "Gand me explosion",
  "Gand me blast",
  "Gand me eruption",
  "Gand me volcano",
  "Gand me earthquake",
  "Gand me tsunami",
  "Gand me hurricane",
  "Gand me tornado",
  "Bhosdike",
  "bsdk",
  "Kutte",
  "Harmkhor",
  "Chutiya",
  "Gandu",
  "Madarchod",
  "Behenchod",
  "Sala",
  "Randi",
  "Lund",
  "Bhadwa",
  "Teri Maa Ki",
  "Teri Behen Ki",
  "Kamina",
  "Harami",
  "Bastard",
  "Dickhead",
  "Asshole",
  "Fuck",
  "Shit",
  "Bitch",
  "Cunt",
  "Prick",
  "Wanker",
  "Twat",
  "Slut",
  "Douchebag",
  "Pussy",
  "Cock",
  "Fucker",
  "Motherfucker",
  "Son of a bitch",
  "Whore",
  "Skank",
  "Scumbag",
  "Pig",
  "Dog",
  "Rat",
  "Snake",
  "Coward",
  "Idiot",
  "Moron",
  "Dumbass",
  "Retard",
  "Loser",
  "Freak",
  "Weirdo",
  "Creep",
  "Pervert",
  "Jerk",
  "Bully",
  "Nerd",
  "Geek",
  "Dork",
  "Lame",
  "Pathetic",
  "Weakling",
  "Sissy",
  "Pansy",
  "Wimp",
  "Crybaby",
  "Spoiled brat",
  "Brat",
  "Bimbo",
  "Airhead",
  "Ditz",
  "Dumb blonde",
  "Gold digger",
  "Attention seeker",
  "Drama queen",
  "Hypocrite",
  "Liar",
  "Cheater",
  "Backstabber",
  "Traitor",
  "Snitch",
  "Tattletale",
  "Gossip",
  "Blabbermouth",
  "Loudmouth",
  "Bigmouth",
  "Know-it-all",
  "Smartass",
  "Wiseass",
  "Show-off",
  "Braggart",
  "Boaster",
  "Egoist",
  "Narcissist",
  "Self-centered",
  "Selfish",
  "Greedy",
  "Glutton",
  "Piggy",
  "Hog",
  "Slob",
  "Messy",
  "Dirty",
  "Filthy",
  "Stinky",
  "Smelly",
  "Gross",
  "Disgusting",
  "Nasty",
];
module.exports = vulgarWords;